/**
 * Kapsamlı BIST hisse sembol listesi (Yahoo `.IS` eki olmadan).
 * Movers (en çok yükselen/düşen) taraması tüm bu evren üzerinde yapılır.
 * Geçersiz/işlem görmeyen semboller Yahoo'dan veri dönmezse sessizce atlanır.
 */

export const BIST_ALL_SYMBOLS = [
  'A1CAP','ACSEL','ADEL','ADESE','ADGYO','AEFES','AFYON','AGESA','AGHOL','AGROT','AGYO','AHGAZ','AKBNK','AKCNS','AKENR','AKFGY','AKFYE','AKGRT','AKMGY','AKSA','AKSEN','AKSGY','AKSUE','AKYHO','ALARK','ALBRK','ALCAR','ALCTL','ALFAS','ALGYO','ALKA','ALKIM','ALMAD','ALTNY','ALVES','ANELE','ANGEN','ANHYT','ANSGR','ARASE','ARCLK','ARDYZ','ARENA','ARSAN','ARTMS','ARZUM','ASELS','ASGYO','ASTOR','ASUZU','ATAGY','ATAKP','ATATP','ATEKS','ATLAS','ATSYH','AVGYO','AVHOL','AVOD','AVPGY','AVTUR','AYCES','AYDEM','AYEN','AYES','AYGAZ','AZTEK',
  'BAGFS','BAHKM','BAKAB','BALAT','BANVT','BARMA','BASCM','BASGZ','BAYRK','BERA','BEYAZ','BFREN','BIENY','BIGCH','BIMAS','BINHO','BIOEN','BIZIM','BJKAS','BLCYT','BMSCH','BMSTL','BNTAS','BOBET','BORLS','BORSK','BOSSA','BRISA','BRKSN','BRKVY','BRLSM','BRMEN','BRSAN','BRYAT','BSOKE','BTCIM','BUCIM','BURCE','BURVA','BVSAN','BYDNR',
  'CANTE','CASA','CCOLA','CELHA','CEMAS','CEMTS','CEOEM','CIMSA','CLEBI','CMBTN','CMENT','CONSE','COSMO','CRDFA','CRFSA','CUSAN','CWENE',
  'DAGHL','DAGI','DAPGM','DARDL','DENGE','DERHL','DERIM','DESA','DESPC','DEVA','DGATE','DGGYO','DGNMO','DIRIT','DITAS','DMSAS','DOAS','DOBUR','DOCO','DOFER','DOGUB','DOHOL','DOKTA','DURDO','DYOBY','DZGYO',
  'EBEBK','ECILC','ECZYT','EDATA','EDIP','EFORC','EGEEN','EGEPO','EGGUB','EGPRO','EGSER','EKGYO','EKIZ','EKOS','EKSUN','ELITE','EMKEL','EMNIS','ENERY','ENJSA','ENKAI','ENSRI','EPLAS','ERBOS','ERCB','EREGL','ERSU','ESCAR','ESCOM','ESEN','ETILR','ETYAT','EUHOL','EUKYO','EUPWR','EUREN','EUYO','EYGYO',
  'FADE','FENER','FLAP','FMIZP','FONET','FORMT','FORTE','FRIGO','FROTO','FZLGY',
  'GARAN','GEDIK','GEDZA','GENIL','GENTS','GEREL','GESAN','GIPTA','GLBMD','GLCVY','GLRYH','GLYHO','GMTAS','GOKNR','GOLTS','GOODY','GOZDE','GRNYO','GRSEL','GRTHO','GSDDE','GSDHO','GSRAY','GUBRF','GUNDG','GWIND','GZNMI',
  'HALKB','HATEK','HATSN','HDFGS','HEDEF','HEKTS','HKTM','HLGYO','HOROZ','HRKET','HTTBT','HUBVC','HUNER','HURGZ',
  'ICBCT','ICUGS','IDGYO','IEYHO','IHAAS','IHEVA','IHGZT','IHLAS','IHLGM','IHYAY','IMASM','INDES','INGRM','INTEM','INVEO','INVES','IPEKE','ISATR','ISBIR','ISBTR','ISCTR','ISDMR','ISFIN','ISGSY','ISGYO','ISKPL','ISMEN','ISSEN','ISYAT','IZENR','IZFAS','IZINV','IZMDC',
  'JANTS',
  'KAPLM','KAREL','KARSN','KARTN','KATMR','KAYSE','KBORU','KCAER','KCHOL','KENT','KERVN','KERVT','KFEIN','KGYO','KIMMR','KLGYO','KLKIM','KLMSN','KLNMA','KLRHO','KLSER','KLSYN','KMPUR','KNFRT','KOCMT','KONKA','KONTR','KONYA','KOPOL','KORDS','KOTON','KOZAA','KOZAL','KRDMA','KRDMB','KRDMD','KRGYO','KRONT','KRPLS','KRSTL','KRTEK','KRVGD','KSTUR','KTLEV','KTSKR','KUTPO','KUVVA','KUYAS','KZBGY','KZGYO',
  'LIDER','LIDFA','LILAK','LINK','LKMNH','LMKDC','LOGO','LRSHO','LUKSK',
  'MAALT','MACKO','MAGEN','MAKIM','MAKTK','MANAS','MARBL','MARKA','MARTI','MAVI','MEDTR','MEGAP','MEGMT','MEKAG','MEPET','MERCN','MERIT','MERKO','METRO','METUR','MGROS','MHRGY','MIATK','MIPAZ','MMCAS','MNDRS','MNDTR','MOBTL','MOGAN','MPARK','MRGYO','MRSHL','MSGYO','MTRKS','MTRYO','MZHLD',
  'NATEN','NETAS','NIBAS','NTGAZ','NTHOL','NUGYO','NUHCM',
  'OBAMS','OBASE','ODAS','ODINE','OFSYM','ONCSM','ONRYT','ORCAY','ORGE','ORMA','OSMEN','OSTIM','OTKAR','OTTO','OYAKC','OYAYO','OYLUM','OZGYO','OZKGY','OZRDN','OZSUB','OZYSR',
  'PAGYO','PAMEL','PAPIL','PARSN','PASEU','PATEK','PCILT','PEHOL','PEKGY','PENGD','PENTA','PETKM','PETUN','PGSUS','PINSU','PKART','PKENT','PLTUR','PNLSN','PNSUT','POLHO','POLTK','PRDGS','PRKAB','PRKME','PRZMA','PSDTC','PSGYO',
  'QNBFB','QNBFL','QUAGR',
  'RALYH','RAYSG','REEDR','RGYAS','RNPOL','RODRG','ROYAL','RTALB','RUBNS','RYGYO','RYSAS',
  'SAFKR','SAHOL','SAMAT','SANEL','SANFM','SANKO','SARKY','SASA','SAYAS','SDTTR','SEGYO','SEKFK','SEKUR','SELEC','SELGD','SELVA','SEYKM','SISE','SKBNK','SKTAS','SMART','SMRTG','SNGYO','SNICA','SNKRN','SNPAM','SODSN','SOKE','SOKM','SONME','SRVGY','SUMAS','SUNTK','SURGY','SUWEN','TABGD','TARKM','TATEN','TATGD','TAVHL','TBORG','TCELL','TDGYO','TEKTU','TERA','TEZOL','TGSAS','THYAO','TKFEN','TKNSA','TLMAN','TMPOL','TMSN','TNZTP','TOASO','TRCAS','TRGYO','TRILC','TSGYO','TSKB','TSPOR','TTKOM','TTRAK','TUCLK','TUKAS','TUPRS','TUREX','TURGG','TURSG','UFUK','ULAS','ULKER','ULUFA','ULUSE','ULUUN','UMPAS','UNLU','USAK','UZERB',
  'VAKBN','VAKFN','VAKKO','VANGD','VBTYZ','VERTU','VERUS','VESBE','VESTL','VKGYO','VKING','VRGYO',
  'YAPRK','YATAS','YAYLA','YBTAS','YEOTK','YESIL','YGGYO','YGYO','YKBNK','YKSLN','YONGA','YUNSA','YYAPI','YYLGD',
  'ZEDUR','ZOREN','ZRGYO',
];

export default BIST_ALL_SYMBOLS;
